version: '3.6'

services:
  grpcapp:
    restart: on-failure
    build: .
    container_name: dj_grpc_benchmark
    volumes: 
      - ./server:/app
    ports:
      - 5050:50051
    environment:
      - CERTIFICATE_GRPC_CRT=${CERTIFICATE_GRPC_CRT}
      - CERTIFICATE_GRPC_KEY=${CERTIFICATE_GRPC_KEY}